name: "📰 Oasis ハイブリッド記事登録"
description: "Oasis ハイブリッド記事 (front matter + 本文) とヘッダー画像 URL/添付を送信して自動追加します。"
title: "[Oasis] YYYYMMDD-your-slug"
labels:
  - oasis-article
body:
  - type: markdown
    attributes:
      value: |
        Oasis ハイブリッド記事を登録します。下記フォームに必要事項を入力し、ヘッダー画像を添付する場合はこの Issue にドラッグ＆ドロップしてください。

        - `articles/oasis/{slug}.md` が作成されます
        - 添付した画像は `generated-images/issue-<number>-<timestamp>/` に保存されます
        - 送信後、自動ワークフローが記事ファイルと画像を生成し、`oasis-sync` が各媒体へ展開します

  - type: input
    id: article_slug
    attributes:
      label: 記事スラッグ (拡張子不要)
      description: |
        ファイル名として利用します。英小文字・数字・ハイフンで 12〜50 文字を推奨します。未入力の場合は発行日ベースで自動生成されます。
      placeholder: 20251015-oasis-sync-0-3-2-release
    validations:
      required: false

  - type: input
    id: publish_date
    attributes:
      label: 公開日 (オプション)
      description: |
        YYYY-MM-DD 形式で入力するとファイル名・front matter の date に利用します。未入力時は作成日の JST を使用します。
      placeholder: 2025-10-15
    validations:
      required: false

  - type: textarea
    id: header_image_url
    attributes:
      label: ヘッダー画像 URL (オプション)
      description: |
        既存の画像 URL があれば指定してください。Issue に画像を添付する場合は空欄のままで構いません。
      placeholder: https://example.com/path/to/header.png
    validations:
      required: false

  - type: textarea
    id: hybrid_markdown
    attributes:
      label: Oasis ハイブリッド Markdown
      description: |
        front matter (`---` で囲まれた zenn/qiita/wordpress セクション) と本文をすべて貼り付けてください。
      render: markdown
      placeholder: |
        ---
        zenn:
          title: ...
        qiita:
          title: ...
        wordpress:
          title: ...
        ---

        ## はじめに
        ...
    validations:
      required: true

  - type: checkboxes
    id: confirmation
    attributes:
      label: 確認事項
      options:
        - label: 添付するコンテンツに必要な権利/ライセンスを保有しています。
          required: true
