name: "🚧🖼️ サムネイル登録（Experimental PNG保存）"
description: "🚧 実験版: 画像を添付/URL指定して PNG としてリポジトリに保存します。"
title: "[Thumb][Experimental] YYYYMMDD-your-slug"
labels:
  - thumbnail-upload
body:
  - type: markdown
    attributes:
      value: |
        下記フォームに入力し、この Issue に **画像をドラッグ＆ドロップで添付** するか、**画像 URL** を指定してください。
        - 保存先: `images/thumbnails/`（変更可）
        - ファイル名: `<slug>.png`
        - 未入力の場合、ファイル名は `YYYYMMDD-oasis-thumb` を自動設定します
        - 添付が複数ある場合は `-1`, `-2` を付けて保存します
        - PNG 以外も自動で PNG へ変換（透過維持）
        - リサイズ（1200x630 / 1280x720）を選べます（短辺フィット＋レターボックス）
        - 備考欄に貼り付けた `<img src=\"...\">` からも画像を収集して保存します（🚧 実験中）

  - type: input
    id: file_slug
    attributes:
      label: 保存ファイル名（拡張子不要）
      description: |
        英小文字・数字・ハイフン推奨。未入力の場合は `YYYYMMDD-oasis-thumb` を自動採番します。
      placeholder: 20251016-oasis-thumb
    validations:
      required: false

  - type: input
    id: dest_dir
    attributes:
      label: 保存ディレクトリ（相対パス）
      placeholder: images/thumbnails
      value: images/thumbnails
    validations:
      required: true

  - type: dropdown
    id: resize_preset
    attributes:
      label: リサイズ（任意）
      description: 短辺フィット＋レターボックス。未選択なら原寸維持。
      options:
        - "なし"
        - "1200x630"
        - "1280x720"
      default: 0
    validations:
      required: false

  - type: input
    id: background_hex
    attributes:
      label: 背景色（レターボックス用・任意）
      description: 例) `#FFFFFF`（空欄なら透明）
      placeholder: "#FFFFFF"
    validations:
      required: false

  - type: input
    id: source_url
    attributes:
      label: 画像 URL（任意）
      description: 例) `https://github.com/user-attachments/assets/...` や外部 URL。添付があれば空欄でOK。
      placeholder: https://github.com/user-attachments/assets/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
    validations:
      required: false

  - type: textarea
    id: notes
    attributes:
      label: 備考（任意・🚧 実験的な `<img>` 埋め込み対応可）
      description: |
        備考欄に `<img width="..." src="https://example.com/...">` のような HTML を貼ると、その画像も保存します。
    validations:
      required: false

  - type: checkboxes
    id: confirmation
    attributes:
      label: 確認事項
      options:
        - label: 添付/指定した画像の権利およびライセンスを保有し、リポジトリへの保存に同意します。
          required: true
