name: "🪄 Oasis Qiita Sync"

on:
  push:
    branches:
      - "main"
    paths:
      - "articles/qiita/**/*.md"
  workflow_run:
    workflows:
      - "🪄 Oasis Article Sync"
    types:
      - completed

permissions:
  contents: read

jobs:
  sync:
    if: ${{ (github.event_name == 'workflow_run' && github.event.workflow_run.conclusion == 'success') || (github.event_name != 'workflow_run' && github.actor != 'oasis-sync[bot]') }}
    runs-on: ubuntu-latest
    env:
      TARGET_REPOSITORY: ${{ vars.QIITA_TARGET_REPOSITORY || 'Sunwood-ai-labs/Qiita-dev' }}
      TARGET_PATH: ${{ vars.QIITA_TARGET_PATH || './public' }}
      TARGET_BRANCH: ${{ vars.QIITA_TARGET_BRANCH || 'main' }}
      SYNC_TOKEN: ${{ secrets.GH_PAT }}
    steps:
      - name: Checkout source repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.event_name == 'workflow_run' && github.event.workflow_run.head_sha || github.ref }}

      - name: Prepare sync script
        run: chmod +x .github/scripts/sync_platform.sh

      - name: Sync new Qiita articles
        env:
          BEFORE_SHA: ${{ github.event.before }}
          PLATFORM: "Qiita"
          SOURCE_PREFIX: "articles/qiita"
          COMMIT_MESSAGE: "Sync new Qiita articles from oasis-sync"
        run: .github/scripts/sync_platform.sh
